### ISSUE TITLE
Use of uninitialized value $pointer in length at /home/wieger/perl5/lib/perl5/JSON/Validator.pm line 434.

### ISSUE THREAD

**Issue by a6502** [jhthorsen/json-validator#104]
When using Perl v5.10.1 (RHEL6 system perl) I get a warning:
`Use of uninitialized value $pointer in length at .../JSON/Validator.pm line 434.`
(using JSON::Validator 2.05)

The behaviour of "lengh(undef)" changed in Perl v5.12, see for example https://www.effectiveperlprogramming.com/2010/09/in-perl-v5-12-lengthundef-returns-undef/

Changing line 434 to:
`if (defined $pointer and length $pointer) {`
would remove this warning. I would appreciate if you could make this change.

**Comment by jhthorsen** [comment]
I'm not very interested in fixing warnings for such an old version of perl, but I just pushed the suggested change, since it seems like a simple thing to do 👍

**Comment by a6502** [comment]
Ok, thx!
