### ISSUE TITLE
speed optimization

### ISSUE THREAD

**Issue by KES777** [jhthorsen/json-validator#109]
if( $value % d ) { ...

is efficient in compare to

    if( ($value / $d) =~ /\.[^0]+$/ ) { ...

https://metacpan.org/source/JHTHORSEN/JSON-Validator-2.06/lib/JSON/Validator.pm#L730

**Comment by jhthorsen** [comment]
That doesn't work. At least I think multipleOf can be floating point numbers. Please let me know if that is incorrect with a link to the spec.
