### ISSUE TITLE
Param "id" is not validate

### ISSUE THREAD

**Issue by svoyakd** [jhthorsen/json-validator#111]
**OK**:
`perl -MJSON::Validator -e 'my $v = JSON::Validator->new(); 
my @errors = $v->validate({id1 => 1, foo => 1}, {type => "object", additionalProperties => 0, properties => {foo => {type => "number"}}});
 use Data::Dumper; print Dumper(@errors), "\n"'`

`$VAR1 = bless( {
                 'message' => 'Properties not allowed: id1.',
                 'path' => '/'
               }, 'JSON::Validator::Error' );`

**BUG**:
`perl -MJSON::Validator -e 'my $v = JSON::Validator->new(); my @errors = $v->validate({id => 1, foo => 1}, {type => "object", additionalProperties => 0, properties => {foo => {type => "number"}}}); use Data::Dumper; print Dumper(@errors), "\n"'`

**Comment by jhthorsen** [comment]
From the commit message:

> I don't like this change, since I was expecting tests to break for JSON::Validator and/or Mojolicious::Plugin::OpenAPI, but no such thing happens when I run `sh ./run-all-tests.sh -j5`

Since there are no tests for that behaviour that I expect, then I will wait for another bug report. At least I have written a test for this issue, so there should be no regression.
