### ISSUE TITLE
Support file:/// URIs

### ISSUE THREAD

**Issue by merkys** [jhthorsen/json-validator#113]
``file:///`` URIs could be supported to reference local files. This seems to be allowed by [JSON Schema docs](http://json-schema.org/latest/json-schema-core.html#rfc.section.8), which defines base URI as URI, therefore, ``file:///`` could be used to resolve and load local files.

**Comment by jhthorsen** [comment]
Why do you want this? You can already reference files on disk by dropping http:// or https:// and everything else should be relative to that imo.

**Comment by merkys** [comment]
[Draft 07](http://json-schema.org/draft-07/json-schema-core.html) requires values of ``$id`` as valid URI references. Strings without scheme identifiers are by no means URIs.

**Comment by jhthorsen** [comment]
But the `$id` value is not a "real thing", meaning it does not have to reference a correct path on disk. It could be `merkys://cool/file.json`.

**Comment by merkys** [comment]
Citing Draft 07:

> The "$id" keyword defines a URI for the schema, and the base URI that other URI references within the schema are resolved against.

Furthermore,

> If present, the value for this keyword MUST be a string, and MUST represent a valid URI-reference [RFC3986].

Therefore, ``$id`` value is as real as URI references are. ``file://`` protocol is standard (for example, ``curl file:///etc/hostname`` will fetch a local file as if it was a remote one) and could in principle be handled. But this is just a feature request.

**Comment by jhthorsen** [comment]
I get what you're saying, but I don't understand the practical use of this. Can you present a real life usecase where this is useful?

**Comment by merkys** [comment]
Use cases of this feature actually are the same as current protocol-less URIs: I have local schemata on my computer and want to validate JSONs against them. However, protocol-less URIs are not valid according to Draft 07: they will fail to validate against the [Core schema meta-schema](http://json-schema.org/draft-07/schema):

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://json-schema.org/draft-07/schema#",
    "title": "Core schema meta-schema",
...
    "properties": {
        "$id": {
            "type": "string",
            "format": "uri-reference"
        },
...
    }
...
}
```

The ``uri-reference`` I believe is nothing else than URI reference according to the [RFC3986](https://tools.ietf.org/html/rfc3986).

**Comment by jhthorsen** [comment]
We're going around in circles. Please make an example that is not supported so I can understand better what is going on.

**Comment by merkys** [comment]
Indeed I was wrong, absolute paths are allowed as values of ``uri-reference``:
```
   uri-reference:  A string instance is valid against this attribute if
      it is a valid URI Reference (either a URI or a relative-
      reference), according to [RFC3986].
```
and RFC3986 reads:
```
   URI-reference = URI / relative-ref

   absolute-URI  = scheme ":" hier-part [ "?" query ]

   relative-ref  = relative-part [ "?" query ] [ "#" fragment ]

   relative-part = "//" authority path-abempty
                 / path-absolute
                 / path-noscheme
                 / path-empty
```
Sorry for so much noise.
