### ISSUE TITLE
Incompatibility with Mojolicious 8.0

### ISSUE THREAD

**Issue by charsbar** [jhthorsen/json-validator#119]
Hello. 
JSON::Validator::OpenAPI::Mojolicious started breaking (esp https://github.com/jhthorsen/json-validator/blob/master/lib/JSON/Validator/OpenAPI/Mojolicious.pm#L43) with this commit in Mojolicious that changed query() behavior https://github.com/mojolicious/mojo/commit/16f564f037519170c9a6a96f41d2ab31736e84e6

I suppose the code should be branched by Mojolicious version (7.94/8.00), or changed to conform with Mojolicious 8.0.

**Comment by jhthorsen** [comment]
Can you explain to me what breaks exactly? I would like a failing test to make sure this doesn't happen again.

Going to close this in favour of #120.

**Comment by charsbar** [comment]
@jhthorsen 
I hope this patch for t/tutorial.t of Mojolicious::Plugin::OpenAPI shows the breakage.

```
--- tutorial.t  2018-10-20 17:46:26.119504719 +0900
+++ tutorial_patch.t    2018-10-20 17:46:31.583737261 +0900
@@ -9,6 +9,7 @@

 $t->get_ok('/api')->status_is(200)->json_is('/info/title', 'Some awesome API');
 $t->get_ok('/api/pets')->status_is(200)->json_is('/pets/0/name', 'kit-e-cat');
+$t->get_ok('/api/pets?age=10')->status_is(200)->json_is('/pets/0/age', '10');

 done_testing;

@@ -42,9 +43,12 @@
     my $input = $c->validation->output;
     my $age   = $c->param("age"); # same as $input->{age}
     my $body  = $c->req->json;    # same as $input->{body}
-
-    # $output will be validated by the OpenAPI spec before rendered
-    my $output = {pets => [{name => "kit-e-cat"}]};
+
+    # Mojo 8.0 breaks here
+    $age = $c->req->query_params->to_hash->{age};
+
+    # $output will be validated by the OpenAPI spec before renderer
+    my $output = {pets => [{name => "kit-e-cat", age => $age}]};
     $c->render(openapi => $output);
   }
```

**Comment by jhthorsen** [comment]
Thanks!
