### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by perlpunk** [jhthorsen/json-validator#14]
```
t/swagger-validate-response-object.t .. Could not load document from data://main/spec.json#:
    Missing or empty input at /perlbrew/perls/perl-5.18.2/lib/site_perl/5.18.2/Swagger2.pm line 386.
```

Installed is Swagger2 0.27

Actually I wanted to upgrade Swagger2, but Swagger2 needs JSON::Validator, and
JSON::Validator needs Swagger2 to test.

Installing JSON::Validator with --notest, then installing Swagger2, and then
running the above test again, it succeeds.
So I guess you should check for a min version of Swagger2 there.

**Comment by jhthorsen** [comment]
Oh. That's rather dumb :disappointed: 

Thanks for reporting this :+1: A new release is on its way to CPAN. Please let me know if the fix is... not a fix, hehe

**Comment by perlpunk** [comment]
thanks =)
