### ISSUE TITLE
Errors in anyOf validation. Do not understand the error messages

### ISSUE THREAD

**Issue by elowy01** [jhthorsen/json-validator#15]
Hi,

It seems that in the validation process of a schema containing anyOf statements, the code issue errors for each of the attributes failing the test, regardless the anyOf branch that the test is.  For example in the script jv-anyof.t in your test suite. In one of the tests:

```
@errors = $validator->validate("too long", $schema);
```

The $validator generate the following message:

anyOf failed: ([0] String is too long: 8/5. [1] Expected number - got string.)'

and I am only interested in knowing that the string is too long and not in the additional 'Expected number -got string' error.

Is there a way of generating only the 'String is to long' error?

Thanks,

ernesto

**Comment by jhthorsen** [comment]
That's an interesting question. I guess it could skip all the tests that doesn't match the input type. Not sure how simple it would be to implement it though.

I'm leaving this open, in case someone wants to give it a go.

**Comment by elowy01** [comment]
Thanks for your reply, I will try to have it a go

Another question, 

Are the numbers in the error messages ([0],[1] and so on) related to the branches of the anyOf tests in a certain way?

Thanks,

e.

**Comment by jhthorsen** [comment]
Yes, the number inside the brackets indicates which rule number that failed.

**Comment by jhthorsen** [comment]
I started working on https://github.com/jhthorsen/json-validator/compare/anyof-oneof-allof-errors yesterday, but it's not my primary target to fix this, since I don't find it _that_ annoying.

If someone wants to complete the work, I would be happy to take a PR.

**Comment by mrenvoize** [comment]
@elowy01 We've been working hard on this today to improve the situation.. everything is now released.. would appreciate your feedback.. I'm looking to close this issue soon.

**Comment by mrenvoize** [comment]
Further work in https://github.com/jhthorsen/json-validator/tree/syntax and

**Comment by mrenvoize** [comment]
Would appreciate your feedback on the rebased branch https://github.com/jhthorsen/json-validator/tree/all-any-one-of-rebase

It's looking promising to me so far.. though there's one outstanding failing test.. jv-object which I'm struggling to pin down.

I'll be running this against the openapi test suits too once this last test is passing again (any pointers would help there.. I'm happy to keep plodding, but you might spot it more easily than me).

I'm also a little bit confused by why a test in jv-oneof results in an anyof type error.. feels like a bug to me.. possibly a oneof error should be the result.

**Comment by KES777** [comment]
I also do not understand what is happen. The error is:

```
Can't load application from file "/home/kes/work/projects/crypto/crypto/bin/crypto": Invalid schema:
/paths/~1login/post/parameters/0: oneOf failed: oneOf failed: Properties not allowed: type. oneOf failed: Properties not allowed: schema. Properties not allowed: schema. Properties not allowed: schema. Properties not allowed: schema. Properties not allowed: schema, description, name, type, in. at /home/kes/work/projects/crypto/crypto/local/lib/perl5/JSON/Validator/OpenAPI.pm line 28.
```

I just add `type: string` into this schema:

```
swagger: '2.0'
info:
  title: Crypto API
  description: Build mobile/desktop client easy to work with Crypto API
  version: 1.0.0
host: localhost
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /login:
    post:
      description: Perfroms user authentication
      produces:
        - application/json
      parameters:
        - name: contact
          description: User's email or phone
          in: body
          type: string
          schema:
            type: string
        - name: password
          description: User's password
          in: body
          schema:
            type: string
      responses:
        '200':
          description: Everything is OK

```

**Comment by jhthorsen** [comment]
Too bad no-one seems to have the time to make this message more understandable 😞

**Comment by KES777** [comment]
I found what the problem actually is. [Issue](https://github.com/OAI/OpenAPI-Specification/issues/1205#issue-236192414)

We can not have more than one `body` parameter

**Comment by jhthorsen** [comment]
Yeah, the "body" is just the whole body. You can't reference parts of the body. "body" is a data-structure, while "formData" is for form fields in a "POST" request.

**Comment by jhthorsen** [comment]
I think #121 will make it easier to implement this. Could you do it on your side by simply doing something like this:

```
my $err = $e->message =~ s!/(\S+)\s!!r;
```

Or can you suggest a better API after #121 is merged?

(Note that there might be changes to #121)
