### ISSUE TITLE
[PATCH] spelling fix in the POD

### ISSUE THREAD

**Issue by gregoa** [jhthorsen/json-validator#18]
In Debian we are currently applying the following patch to
JSON-Validator.
We thought you might be interested in it too.

    Description: spelling fix in the POD
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-04-17
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libjson-validator-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by jhthorsen** [comment]
Thank you! 👍

**Comment by gregoa** [comment]
On Sun, 17 Apr 2016 09:05:14 -0700, Jan Henning Thorsen wrote:

> Thank you! 👍 

Thanks to you!

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Tom Waits: Empty Pockets & Broken Bicycles
