### ISSUE TITLE
remove 'replace' feature in bundle

### ISSUE THREAD

**Issue by karenetheridge** [jhthorsen/json-validator#194]
I was reading https://github.com/json-schema-org/json-schema-spec/issues/514 and https://github.com/json-schema-org/json-schema-spec/pull/628 and realized that the 'replace' option in `bundle()` is treating `$ref` like an inclusion, not a delegation, which is wrong.  `$ref`s should always remain as-is, so its sub-schema can be delegated to (evaluated in place), as described in that ticket.

I see that this feature was already deprecated once, in version 3.10, and then undeprecated although left undocumented, so there shouldn't be any serious ramifications here. So this ticket is mostly informational at this point.

**Comment by jhthorsen** [comment]
I'm using "replace" in JSON::Validator::OpenAPI::Mojolicious, so this cannot be done before I merge #189 and implement subclasses for OpenAPIv2 and OpenAPIv3.

**Comment by jhthorsen** [comment]
This feature is no longer present in #251.
