### ISSUE TITLE
Set min perl version to 5.016

### ISSUE THREAD

**Issue by neilb** [jhthorsen/json-validator#250]
* JSON::Validator version: 4.20
* Perl version: *
* Operating system: *

Hi,

You should nump your perl min version to 5.16 (it's currently set to 5.10.1), as Mojolicious has their min perl version set to that, and json-validator depends on Mojo.

Cheers,
Neil

**Comment by jhthorsen** [comment]
I thought that was done implicit *since* J::V is depending on Mojolicious. Thanks for teaching me something new 👍
