### ISSUE TITLE
Lots of warnings when processing Accept header

### ISSUE THREAD

**Issue by xurc** [jhthorsen/json-validator#252]
Presumably after this commit there were a lot of warnings in the log

https://github.com/jhthorsen/json-validator/commit/f9c20132ad38c7152e5faa4a1e9ee9ead5b71fb8

* JSON::Validator version: 4.20
* Perl version: 5.28.1
* Operating system: Debian GNU/Linux 10

### Steps to reproduce the behavior
Make any GET (at least) request with header

`Accept: application/json, text/plain, */*`

### Expected behavior
No warnings in log

### Actual behavior
```
Use of uninitialized value $header_map{"*/*"} in numeric comparison (<=>) at /usr/local/share/perl/5.28.1/JSON/Validator/Util.pm line 98.
Use of uninitialized value $header_map{"application/json"} in numeric comparison (<=>) at /usr/local/share/perl/5.28.1/JSON/Validator/Util.pm line 98.
Use of uninitialized value $header_map{"*/*"} in numeric comparison (<=>) at /usr/local/share/perl/5.28.1/JSON/Validator/Util.pm line 98.
Use of uninitialized value $header_map{"text/plain"} in numeric comparison (<=>) at /usr/local/share/perl/5.28.1/JSON/Validator/Util.pm line 98.
Use of uninitialized value $header_map{"text/plain"} in numeric comparison (<=>) at /usr/local/share/perl/5.28.1/JSON/Validator/Util.pm line 98.
Use of uninitialized value $header_map{"application/json"} in numeric comparison (<=>) at /usr/local/share/perl/5.28.1/JSON/Validator/Util.pm line 98.
```

**Comment by jhthorsen** [comment]
I think it's very strange for an API request to not specify what it wants, but nevertheless the bug is fixed 👍

**Comment by xurc** [comment]
> I think it's very strange for an API request to not specify what it wants
This appeared in the logs on the dev environment just during the development process.

> but nevertheless the bug is fixed 👍
Thank you so much!
