### ISSUE TITLE
multipleOf is broken for floats

### ISSUE THREAD

**Issue by melhesedek** [jhthorsen/json-validator#35]
`$v->validate({validNumber => 2.01})` fails with `Not multiple of 0.01.` at `/validNumber` with the following schema:

```
{
  "type": "object",
  "properties": {
    "validNumber": {
      "type": "number",
      "multipleOf": 0.01
    }
  }
}
```

**Comment by jhthorsen** [comment]
Closed by #33.

**Comment by melhesedek** [comment]
Still reproducible, separate issue from #33. According to the [JSON Schema draft](http://json-schema.org/latest/json-schema-validation.html#anchor14), `2.01` is a valid `multipleOf` `0.01`, cause `2.01/0.01` is an integer.

[This check](https://github.com/jhthorsen/json-validator/blob/fd5030593a2ee9b675a7045f814e4c8b13340d4c/lib/JSON/Validator.pm#L538) fails us due to some [float magic](http://perldoc.perl.org/functions/int.html):

    $ perl -E 'say 2.01/0.01'
    201
    $ perl -E 'say int(2.01/0.01)'
    200

**Comment by jhthorsen** [comment]
Ah! I misunderstood. Thanks for making this clear.

**Comment by jhthorsen** [comment]
Never mind the test. I didn't mean to push it.

**Comment by jhthorsen** [comment]
It's a rather hackish fix, but it seems to do the trick. Let me know if you can provoke any other failing cases.
