### ISSUE TITLE
Integer path param ending with \w warns and passes validation

### ISSUE THREAD

**Issue by ugexe** [jhthorsen/json-validator#36]
(Note: I'm using `Mojolicious::Plugin::OpenAPI`, so it's possibly a bug from there)

I have an integer path parameter: `"parameters" : [ { "in": "path", "name": "id", "type": "integer" } ],`, and when I give it a value such as "42a" I get an unexpected warning and there is no validation failure.

I logged the value of $value on the lines before and after the line causing the warning and include it in the output below:

    perl -Ilocal/lib/perl5 -Ilib script/swagger.pl get /document/42a
    "42a" #L79 `p $value;`
    Argument "\x{34}\x{32}..." isn't numeric in addition (+) at local/lib/perl5/JSON/Validator/OpenAPI.pm line 80.
    42    #L81 `p $value;`

    # "\x{34}\x{32}" is 42

Seems like it might be an issue with coercing somewhere, but I couldn't figure out how to golf it

    perl -E 'my $x = "42a"; $x += 0; say $x'
    42

**Comment by jhthorsen** [comment]
Fixed by using `Scalar::Util::looks_like_number()`

Thank you!
