### ISSUE TITLE
$ref support and multi-file specifications

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/json-validator#4]
_From @mrenvoize on September 16, 2015 16:11_

I was hoping to create a structure something along the lines described [here](http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html)

But this seems to be incompatible with the current implementation of the mojo plugin structure.. any thoughts on how to achieve similar with this swagger implementation?

_Copied from original issue: jhthorsen/swagger2#33_

**Comment by mrenvoize** [comment]
_From @jhthorsen on September 17, 2015 14:12_

You need to show code or even better create a failing test. I don't understand what doesn't work. $ref is indeed supported and there are multiple tests for it. I might have bugs, but I need further information to understand what that might be.

**Comment by mrenvoize** [comment]
Found the time to build an example now, I've got a test app based upon your Blog demo now on https://github.com/mrenvoize/swagger-test

Try running:

script/blog routes

You'll see the linked files are not picked up..  ./definitions/index.json

**Comment by mrenvoize** [comment]
_From @jhthorsen on September 21, 2015 10:28_

So the issue is "Support for $ref to relative locations/file/url" ?

**Comment by mrenvoize** [comment]
pretty much.. sorry, I suppose most of the chatter went on on irc.. I should have cloned it here

**Comment by mrenvoize** [comment]
I suppose a 'spec' is in order; I see the following scenarios for $ref usage:

#### private spec files
as in the example, a spec file and associated definitions files within the app but not publicly served

#### public spec files
spec + definition files under either /template or /public directories and thus served by Mojolicious server when run up (with either full or relative urls in the refs themselves created via a template process perhaps?)

Does that make sense?

**Comment by mrenvoize** [comment]
_From @jhthorsen on September 21, 2015 11:40_

I need a proper spec. I'm not sure if I read the spec correct, but I don't think there's anything against this functionality. On the other hand, this is not something I want to jump into before I fully understand it or see other implementations that does the same thing.

http://json-schema.org/latest/json-schema-core.html#anchor30

**Comment by mrenvoize** [comment]
Moved the issue...

Whilst trying to write a test I've confused myself even further.. looks like relative paths DO work.. but there seems to be a bug in actually loading the specs as highlighted by the failing test in my pull request.

**Comment by jhthorsen** [comment]
I think 5d7d9db should resolve this. Please try it out and let me know what you think.

**Comment by jhthorsen** [comment]
I think the link below describes that we was right about how we thought it should be implemented: http://spacetelescope.github.io/understanding-json-schema/structuring.html#the-id-property
