### ISSUE TITLE
Nested $ref error

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/json-validator#5]
When using nested $refs.. i.e. ref to one file that refs another file I am seeing the following error in the console:

Use of uninitialized value $pointer in substitution (s///) at /home/rebus/.plenv/versions/5.20.2/lib/perl5/site_perl/5.20.2/Mojo/JSON/Pointer.pm line 15, <DATA> line 2231.

I've written a test that shows this: https://github.com/mrenvoize/json-validator/tree/nested-refs

**Comment by jhthorsen** [comment]
I think 5d7d9db should resolve this. Please try it out and let me know what you think.
