### ISSUE TITLE
Make boolean coercion work for B::SVp_IOK values

### ISSUE THREAD

**Issue by fabzzap** [jhthorsen/json-validator#56]
There's a line in `_validate_type_boolean`

    and (B::svref_2object(\$value)->FLAGS & B::SVp_NOK or $value =~ /^(true|false)$/))

so that values that have the flag B::SVp_NOK on are coerced but other values are not. In other parts of the code, `B::svref_2object(\$value)->FLAGS & (B::SVp_IOK | B::SVp_NOK)` is checked instead, and this makes more sense. Now, with coerce on, 0.5 is considered a valid boolean value but 2 is not, for example.

Why not change `_validate_type_boolean` so  it checks `B::SVp_IOK | B::SVp_NOK`?

**Comment by jhthorsen** [comment]
Good question. Not sure why it doesn't coerce all values, but the test I cleaned up in 0abd552 shows how I thought it should work, but I can't remember why right now 😞

**Comment by jhthorsen** [comment]
Could you write some tests and make a PR? I have a hard time seing how this will actually look.

**Comment by jhthorsen** [comment]
Closing this because of lack of interest and I don't have time to look at it myself.
