### ISSUE TITLE
The error spec is cached twice?

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/json-validator#61]
We have somehow ended up with the internal error document cached twice in the module.

`json-validator/lib/JSON/Validator/cache/49c95b866e40f788892a7fb3c816b0e8`
`json-validator/lib/JSON/Validator/cache/eaa832720f36cff0abc20c05236a9cd9`

**Comment by jhthorsen** [comment]
Yeah. It's because there are two URLs mapping to the same document, since I had to move it.
