### ISSUE TITLE
1.03 doesn't allow remote schemas with ids

### ISSUE THREAD

**Issue by wbazant** [jhthorsen/json-validator#74]
Test case:
https://github.com/wbazant/json-validator/commit/27de57c1ae2c5022422919b69963cc4b32b845a0
```
#   Failed test 'remote ref - remote ref valid'
#   at t/acceptance.t line 52.
#          got: '0'
#     expected: '1'
# Invalid schema:
# /id: Does not match uri format. at /Users/wbazant/dev/json-validator/lib/JSON/Validator.pm line 70.
# 	JSON::Validator::load_and_validate_schema('JSON::Validator=HASH(0x7f91a1d0ccf8)', 'HASH(0x7f91a16efa18)') called at t/acceptance.t line 46
# 	eval {...} called at t/acceptance.t line 45
```

**Comment by jhthorsen** [comment]
Is that really a valid ID? Can you point me to the specification?

**Comment by wbazant** [comment]
Sure, that's fair to ask, especially that I didn't check this before submitting the issue! It is:

http://json-schema.org/schema says an id is a uri-reference: http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3.7

https://tools.ietf.org/html/rfc3986 says an uri-reference can be an URI or a relative-ref (4.1) and (4.2) gives this grammar for relative-ref:
```
relative-ref  = relative-part [ "?" query ] [ "#" fragment ]

      relative-part = "//" authority path-abempty
                    / path-absolute
                    / path-noscheme
                    / path-empty
```

**Comment by jhthorsen** [comment]
I've created a new branch that I'm working on: https://github.com/jhthorsen/json-validator/compare/bug/id-keyword

Could you take a look? It's a work in progress, so you can also wait. (I'll notify you when I make it work)

**Comment by wbazant** [comment]
I had a look! I tried to think abstractly about it, I think the hardest
piece to add is that _load_schema   needs to at least conceptually recurse
on itself and this doesn't (or at least I can see no way in which it does
now)

I'm talking about the first subpart of the problem - making  t/resolve.t work
- parse a schema, possibly with refs, and produce an internal
representation of the schema, without the refs.

Now you have this call stack:
schema
_resolve
_load_schema
...
_load_schema_from_text

together with storing the loaded pieces but it doesn't recurse anywhere,
unless I'm reading it wrong?


I believe the solution has to recurse on itself and I think it has to
involve knowing how to insert the partial results (that got downloaded and
resolved) into the result structure.

I tried to prototype what I mean in Haskell:
https://repl.it/MT7C/19

By the way I find it much easier to follow the different methods of loading
schema now, they really clearly delegate to - eventually
- _load_schema_from_text. But if _load_schema loads a document with a ref
inside it, I see nothing that makes the code resolve that ref, it only
returns it on (_resolve L 205 ) and then stores the pieces.


2017-10-08 15:08 GMT+01:00 Jan Henning Thorsen <notifications@github.com>:

**Comment by wbazant** [comment]
I made a sketch, which like the previous prototype also ignores everything
about the problem that isn't about loading refs:
http://rextester.com/HQJG49770

Then I thought about how it won't work, and it won't work on documents that
reference pieces of themselves. Then I realised why you need the store, and
why you're getting and setting from it :) so I think you already know that.

I made a fairly devious test case that fails this - a simple one is just
{ref: #}, and the current code handles that well. This fails in the current
project too:
https://github.com/wbazant/json-validator/commit/46cade5a663fc865563f1e57f285d9dad92a50f6

I think it's an okay schema, referring to an okay JSON: in the first
example "#/definitions/c" is like  "#/definitions/a/0" in the second.

I hope you've found this if not helpful then at least amusing.

Best regards,
Wojtek

2017-10-09 16:48 GMT+01:00 Wojciech Bażant <wojciech.bazant@gmail.com>:

**Comment by jhthorsen** [comment]
I've opened a pull request now. Please have a look at #79.
