### ISSUE TITLE
Internalization of validation messages

### ISSUE THREAD

**Issue by vividsnow** [jhthorsen/json-validator#86]

**Comment by jhthorsen** [comment]
I'm going to close this issue unless someone contributes or creates a plan for how this can be accomplished. Also, I want to know why this is important and which problem/usecase it fixes.

**Comment by vividsnow** [comment]
Hello

I propose to use Locale::Maketext in statements like these:
https://github.com/jhthorsen/json-validator/blob/master/lib/JSON/Validator.pm#L174
https://github.com/jhthorsen/json-validator/blob/master/lib/JSON/Validator.pm#L497

This feature will give ability to display localized validation errors in UI

**Comment by jhthorsen** [comment]
You should rather translate the errors in your UI. Also, displaying these errors directly to the end user will be confusing, unless they are extremely technical.
