### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by 27escape** [jhthorsen/json-validator#9]
Trying to install JSON::Validator and it cannot as Swagger2 is not available, cannot install Swagger2 as it requires JSON::Validator :smile:

Obviously I can cpanm --force to get it through, but that is only a stop gap measure

**Comment by jhthorsen** [comment]
It's probably because it's not fully distributed to your local cpan mirror. Can you try this:

    $ cpanm -M https://cpan.metacpan.org Swagger2

**Comment by jhthorsen** [comment]
Also, the https://metacpan.org/pod/JSON::Validator distro does not depend on Swagger2, so there's something not right with the title in this issue.
