### ISSUE TITLE
Custom keywords support?

### ISSUE THREAD

**Issue by foobargeez** [jhthorsen/json-validator#90]
Hello,
I am wondering if I can use `pattern` in a case *in*sensitive way and I don't see an option.  I see a  similar requirement addressed in https://github.com/epoberezkin/ajv-keywords#regexp and was wondering if something similar could be added to JSON::Validator.

Thanks!

**Comment by jhthorsen** [comment]
What about ‘/(?i)whatever/‘ ?

**Comment by jhthorsen** [comment]
Closing this because because of inactivity and because I think my suggestion will work.
