### ISSUE TITLE
This document should get rejected by this schema, but it doesn't

### ISSUE THREAD

**Issue by akarelas-pt** [jhthorsen/json-validator#92]
My case (complete with perl code) is here:

https://gist.github.com/akarelas-pt/cca011dec6bf3c4709aa0a4ccabb11fc

**Comment by jhthorsen** [comment]
I created a failing test here: 81ac60d

It's very, very strange... Will investigate further.

**Comment by akarelas-pt** [comment]
@mohawk2

**Comment by jhthorsen** [comment]
See #93 for fix.

**Comment by jhthorsen** [comment]
Fixed by be77d24.
