### ISSUE TITLE
How does "ref" / bundles work with JSON::Validator?

### ISSUE THREAD

**Issue by ryandietrich** [jhthorsen/json-validator#95]
I'd like to define a schema for one particular sub-structure in a file, and then re-use that in multiple schemas elsewhere.  It appears that JSON::Validator supports this concept, but I can't figure out how it works (the test bundle.t didn't seem to enlighten me).

Basically the pattern I'm after here is:

car.json <- defines what is valid to be a car.

assembly_plant.json <- includes car.json uses it so it doesn't have to re-define it locally.
auto_showroom.json <- includes car.json, uses it so it doesn't have to re-define it locally.

This way I can alter car.json, and assembly_plant/auto_showroom will update accordingly.

Is this a thing?  Do you have an example you can share?

**Comment by jhthorsen** [comment]
I suggest asking questions like this in the #swagger channel on irc.perl.org.

Anyway: You could check out these resources:

* https://github.com/jhthorsen/json-validator/blob/master/t/spec/with-relative-ref.json
* https://github.com/jhthorsen/json-validator/blob/master/t/spec/with-deep-mixed-ref.json
* https://spacetelescope.github.io/understanding-json-schema/structuring.html
* http://json-schema.org/latest/json-schema-core.html#rfc.section.8

**Comment by ryandietrich** [comment]
Thank you, I understand now.
